#! /bin/sh
export PATH=/usr/local/bin:$PATH
npx commitlint < $1
status=$?
if [ $status -gt 0 ]
then
        # echo "Commit message does not follow conventional commit message spec"
        # echo 'Please use "npx cz" instead of "git commit" command to format commit message according to conventional commit message spec'
        
        # Uh-oh, this is not a conventional commit, show an example and link to the spec.
        echo "\e[31mThe commit message does not meet the Conventional Commit Standard\e[0m"
        echo "An example of a valid message is: "
        echo "  feat(login): add the 'remember me' button"
        echo '\nPlease use \e[31m"npx cz"\e[0m instead of \e[31m"git commit"\e[0m command to format commit message according to conventional commit message spec'
        echo "For more details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
fi
exit $status